### ISSUE TITLE
static-eval is to old and triggers npm audit

### ISSUE THREAD

**Issue by taeguscromis** [SeanSobey/ChartjsNodeCanvas#10]
Please check the dependencies as you are using a very old version of "static-eval" package. This is dangerous and could be exploited. I advise to update it if you can or avoid that dependency. 

2.0.0 and newer version do not have the problem anymore.

**Comment by SeanSobey** [comment]
Hi! Thanks for the report

`static-eval` was a dependency of `fresh-require` but was not actually used by that package or this one even, so while not ideal I don't think there was actually any vulnerability open to exploit in that specific case.

But never-the-less, since it seems `fresh-require` is no longer maintained I have replaced it with a local implementation, removed it as a dependency and pushed up a new version.

Thanks again

**Comment by taeguscromis** [comment]
Thank you.
