### ISSUE TITLE
Chart is not defined - [chartjs-plugin-piechart-outlabels]

### ISSUE THREAD

**Issue by brunoricardore** [SeanSobey/ChartjsNodeCanvas#16]
I'm trying to register the chartjs-plugin-piechart-outlabels, but even passing for all the methods, the error persists:  ReferenceError: Chart is not defined.

What can I do to register this plugin?

**Comment by SeanSobey** [comment]
Hi, I don't have the ability to test this at the moment, but looking at the [src](https://unpkg.com/chartjs-plugin-piechart-outlabels@0.1.4/dist/chartjs-plugin-piechart-outlabels.js) for the plugin it looks like you need to use the 2nd option for [registering older plugins](https://github.com/SeanSobey/ChartjsNodeCanvas#older-plugins).

Eg:
```js
const chartJsFactory = () => {
	const chartJS = require('chart.js');
	require('chartjs-plugin-piechart-outlabels');
        // Clear the require cache so to allow `CanvasRenderService` seperate instances of ChartJS and plugins.
	delete require.cache[require.resolve('chart.js')];
	delete require.cache[require.resolve('chartjs-plugin-piechart-outlabels')];
	return chartJS;
};
const canvasRenderService = new CanvasRenderService(width, height, undefined, undefined, chartJsFactory);
```

**Comment by skyerh** [comment]
No... it's not working...
It is still showing ReferenceError: Chart is not defined.

**Comment by SeanSobey** [comment]
Having looked at the [source](https://unpkg.com/chartjs-plugin-piechart-outlabels@0.1.4/dist/chartjs-plugin-piechart-outlabels.js) for this [plugin](https://github.com/Neckster/chartjs-plugin-piechart-outlabels) I have found the issue. The plugin implements a global import mechanism at the top importing Chart.JS into a variable `Chart$1`, but there is a section of code that expects the global variable `Chart`, which is the error stack you see.

While my lib does provide workarounds for legacy plugins this would require 2 mutually exclusive workarounds. The correct fix would be to have `chartjs-plugin-piechart-outlabels` reference `Chart$1` instead of `Chart`, I would suggest a bug report, pull request, or at worst fork of that library.
