### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by danny6514** [SeanSobey/ChartjsNodeCanvas#24]
My server uses chartjs-node-canvas to generate many charts into a pdf. I ran the chrome heap profiler and noticed that each time I generate the report, I get a significant amount of chart related records with high retained sizes. Below are the screenshots:

<img width="1189" alt="Screen Shot 2019-11-21 at 12 17 39 AM" src="https://user-images.githubusercontent.com/1629317/69319731-981a2f00-0bf4-11ea-8a52-7adfa1514d4c.png">
<img width="918" alt="Screen Shot 2019-11-21 at 12 19 47 AM" src="https://user-images.githubusercontent.com/1629317/69319756-a6684b00-0bf4-11ea-930c-4276d91cf36f.png">

Code usage:
```
rangeLine(min, max, value).then(chart => {
  ...
});

const rangeLine = (min, max, val) => {
  const canvasRenderService = new CanvasRenderService(170, 30);
  return canvasRenderService.renderToBuffer({
    type: "line",
    data: {
      datasets: [
        {
          pointBackgroundColor: "white",
          borderColor: "black",
          data: [
            {
              x: min,
              y: 0
            },
            {
              x: mid,
              y: 0
            },
            {
              x: max,
              y: 0
            }
          ]
        },
        {
          pointBackgroundColor: 'blue',
          pointRadius: 10,
          pointStyle: "rectRot",
          data: [
            {
              x: val,
              y: 0
            }
          ]
        }
      ]
    }
  });
};
```

Version: v2.4.0

**Comment by SeanSobey** [comment]
Hi, thanks for raising this issue.

This library uses external resources via [canvas](https://github.com/Automattic/node-canvas), but the API is designed to manage this and there are [tests](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.e2e.spec.ts#L16) to monitor for leaks.

That said I should maybe add some documentation as to how to use this library correctly and ensure proper memory management.

In your case, I don't think there are any leaks but the garbage collection will have a lot of work. The `CanvasRenderService` instance should be reused so you don't instantiate a new canvas for every time you make a call:

```js
// Each instance creates its own canvas
const canvasRenderService = new CanvasRenderService(170, 30);

rangeLine(min, max, value).then(chart => {
  ...
});

const rangeLine = (min, max, val) => {
  return canvasRenderService.renderToBuffer({
  ...
  });
};
```

**Comment by seth2810** [comment]
Hi, Sean. Could you explain what reason to have "fresh" versions of `canvas` module functions for each render service instance and why you call `freshRequire` twice https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.ts#L44-L45 instead of reading required `createCanvas ` / `registerFont ` functions from the module in single call and assign it to instance properties after?

**Comment by SeanSobey** [comment]
Hi seth.

`freshRequire` is needed to isolate `canvas` instances since actions in the library's API mutate global state inside, canvas width and height for example. This way each `CanvasRenderService` encapsulates  that state for you, at the cost of a bit of complexity with things like chart pugins, fonts etc.

The code you [mention](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.ts#L44-L45) does actually appear like a bug, but could possibly be for some reason. I will investigate more tomorrow to confirm but yeah looking at it I can't think of why there would be seperate instances for font and the canvas.

**Comment by SeanSobey** [comment]
Investigated this and strangely loading separate instances did not affect the font loading in my (limited) testing. I suspect it may be registering fonts at an OS level. Nevertheless I did fix that anyway and all tests passed fine, so the latest version should be more consistent now.

**Comment by seth2810** [comment]
Thank you, Sean.
