### ISSUE TITLE
support nodejs@12

### ISSUE THREAD

**Issue by antirek** [SeanSobey/ChartjsNodeCanvas#25]
I got error:
 Unsupported engine for chartjs-node-canvas@2.4.1: wanted: {"node":"11.14.0","npm":"6.7.0"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: chartjs-node-canvas@2.4.1

how I can update chartjs-node-canvas to nodejs@12?

**Comment by SeanSobey** [comment]
There are only upstream dependencies that require specific node versions:

* [canvas](https://github.com/Automattic/node-canvas) is the main one, historically very fussy about node version, but seems to now have support for `12.13.1`.
* [memwatch](https://github.com/eduardbcom/node-memwatch), used to check for memory leaks in the tests, this currently has an [issue](https://github.com/eduardbcom/node-memwatch/issues/2). Since it looks to be no longer maintained I will look for a replacement.

**Comment by IlyaSemenov** [comment]
@antirek You can use `yarn --ignore-engines` for the time being. Works fine in Node 12 for me.

**Comment by SeanSobey** [comment]
I have disabled the memory leak tests for now and updated references, [2.4.1](https://github.com/SeanSobey/ChartjsNodeCanvas/releases/tag/2.4.1) should now work for you.
