### ISSUE TITLE
Issues with modules

### ISSUE THREAD

**Issue by Burday** [SeanSobey/ChartjsNodeCanvas#36]
Hey, when I run your package, I immediately get the following error:
`<dir>\node_modules\canvasjs\src\main\index.js:15`
import Charts from `'../core/charts';`
SyntaxError: Cannot use import statement outside a `module``

I haven't modified anything in that file. Any help?

**Comment by SeanSobey** [comment]
Hi,

Hmm hard to tell from that error. It looks like you are using/trying to use [canvasjs](https://www.npmjs.com/package/canvasjs) instead of the prescribed [chart.js](https://www.npmjs.com/package/chart.js) with this lib?

If not maybe you could link to your repo or post the code and package.json file you are running?

**Comment by Burday** [comment]
Hey, managed to fix it by updating the package, despite it only being installed like 5 hours ago. Somehow worked. Gonna close this issue for now
