### ISSUE TITLE
Animation options support

### ISSUE THREAD

**Issue by jpoh97** [SeanSobey/ChartjsNodeCanvas#6]
I'm trying to put values to bars and I'm using the onAnimationComplete option from charts.js (https://www.chartjs.org/docs/latest/configuration/animations.html#animation-callbacks). Examples: 

- http://jsfiddle.net/uh9vw0ao/
- https://jsfiddle.net/4mxhogmd/1/

But it doesn't work. How can I put each value to the bar chart?

```
options: {
        onAnimationComplete: function () {

            var ctx = this.chart.ctx;
            ctx.font = this.scale.font;
            ctx.fillStyle = this.scale.textColor
            ctx.textAlign = "center";
            ctx.textBaseline = "bottom";
    
            this.datasets.forEach(function (dataset) {
                dataset.bars.forEach(function (bar) {
                    ctx.fillText(bar.value, bar.x, bar.y - 5);
                });
            })
        }, 
```

**Comment by SeanSobey** [comment]
Firstly, there is a community extension that does this if you have not seen it yet, [chartjs-plugin-datalabels](https://github.com/chartjs/chartjs-plugin-datalabels).

This does not work since chart animation (and responsive resize) is disabled by this library. This is necessary since the animation API's required are not available in node/canvas (this is not a browser environment after all). I will add some documentation highlighting this limitation. Note this is the same as:
```js
Chart.defaults.global.animation = false;
Chart.defaults.global.responsive = false;
```

To achieve what you want you should use instead the `afterDatasetsDraw` plugin hook:
```js
var myChart = new Chart(ctx, {
  ...
    plugins: [{
        afterDatasetsDraw: function(chartController, options) {
			var ctx = chartController.chart.ctx;

			ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
			ctx.textAlign = 'center';
			ctx.textBaseline = 'bottom';

			chartController.data.datasets.forEach(function (dataset, i) {
				var meta = chartController.getDatasetMeta(i);
				meta.data.forEach(function (bar, index) {
					var data = dataset.data[index];                            
					ctx.fillText(data, bar._model.x, bar._model.y - 5);
				});
			});
        }
    }]
});
```
See an updated [fiddle](https://jsfiddle.net/SeanSobey/dyo4pmq2/2/).
