### ISSUE TITLE
Problem with Date format in a axis label 

### ISSUE THREAD

**Issue by ItaloOliveiraF** [SeanSobey/ChartjsNodeCanvas#74]
I'm trying use the time format in X axis to convert a timestamp in a date string to labels. I'm using the following code.

`
"options": {
           "scales": {
                    "x": {
                            "type": 'time',
                        }
            }
 }
`

But this always return the error:  

> This method is not implemented: Check that a complete date adapter is provided.

I tried use a adapter, but without sucess.

chartjs-node-canvas version: 3.2.0
chart.js version: 3.3.2
nodejs version: 14.7.0

**Comment by SeanSobey** [comment]
I am not aware of this issue appearing before or have seen date adaptors, most likely since Chart.js `3.x.x` is not yet officially supported. That said I had a quick look at the documentation and I suspect your issue after loading adaptors is the way this lib sandboxes chart.js instances. There are mechanisms to load plugins that should address this, see the [plugins docs](https://github.com/SeanSobey/ChartjsNodeCanvas#older-plugins), but I have not tested these yet with date adaptors:

Eg, for [chartjs-adapter-moment](https://github.com/chartjs/chartjs-adapter-moment), looks like it 'requires' chart.js itself, so this should work, assuming you have `chart.js`, `moment` and `chartjs-adapter-moment` installed:

```
const chartJSNodeCanvas = new ChartJSNodeCanvas({ width, height, plugins: {
    globalVariableLegacy: ['chartjs-adapter-moment']
} });
```

**Comment by ItaloOliveiraF** [comment]
I tried it that way and it worked. Thank you.
